#ifndef __DRIVER_ROTARY_ENCODER_H__
#define __DRIVER_ROTARY_ENCODER_H__

#include "main.h"

#define ROTARY_ENCODER_GRANULARITY 2

enum RotaryEncoderMode {
  ROTARY_ENCODER_MODE_NORMAL,
  ROTARY_ENCODER_MODE_INVERT_BOTH,
  ROTARY_ENCODER_MODE_INVERT_VERT_HORZ_NORM,
  ROTARY_ENCODER_MODE_INVERT_VERT_HORZ_ALT,
  ROTARY_ENCODER_MODE_VERT_NORM_HORZ_INVERT,
  ROTARY_ENCODER_MODE_LAST = ROTARY_ENCODER_MODE_VERT_NORM_HORZ_INVERT
};

void rotaryEncoderInit(void);

int32_t rotaryEncoderGetValue();

int8_t rotaryEncoderGetAccel();
void rotaryEncoderResetAccel();
#endif

